apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kind
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - hostPort: 8080
    containerPort: 8080
    protocol: TCP
  - hostPort: 30100
    containerPort: 30100
    protocol: TCP
- role: worker
  extraPortMappings:
  # operator & webhook 
  - hostPort: 80
    containerPort: 80
    protocol: TCP
  - hostPort: 8443
    containerPort: 8443
    protocol: TCP
  - hostPort: 10080
    containerPort: 10080
    protocol: TCP