apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kind
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraMounts:
  - hostPath: /
    containerPath: /mnt/root
  extraPortMappings:
  - hostPort: 30100
    containerPort: 15021
    protocol: TCP
  - hostPort: 30110
    containerPort: 8080
    protocol: TCP
  - hostPort: 30120
    containerPort: 8443
    protocol: TCP
  - hostPort: 30230
    containerPort: 31400
    protocol: TCP
  - hostPort: 30140
    containerPort: 15443
    protocol: TCP
  - hostPort: 80
    containerPort: 80
    protocol: TCP
  - hostPort: 443
    containerPort: 443
    protocol: TCP