apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kind
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - hostPort: 8080
    containerPort: 8080
    protocol: TCP
  - hostPort: 30100
    containerPort: 30100
    protocol: TCP
  - hostPort: 30200
    containerPort: 30200
    protocol: TCP
- role: worker
  extraMounts:
  - hostPath: /
    containerPath: /mnt/root
  - hostPath: /opt
    containerPath: /mnt/volume_storage_mount 
  extraPortMappings:
  # referecnce
  - hostPort: 80
    containerPort: 80